#!/usr/bin/env python3
"""Parameters for v4: positive mechanical swivel end stops."""

from __future__ import annotations

import math

import geometry_model as G
import v2_params as V2


STOP_TARGET_DEG = 15.0
STOP_RADIUS = 112.0

ROTOR_STOP_TAB_RADIAL_LENGTH = 18.0
ROTOR_STOP_TAB_TANGENTIAL_WIDTH = 14.0
ROTOR_STOP_TAB_Z0 = 6.0
ROTOR_STOP_TAB_HEIGHT = 10.0

ROTOR_STOP_SPOKE_R0 = 70.0
ROTOR_STOP_SPOKE_R1 = 108.0
ROTOR_STOP_SPOKE_WIDTH = 8.0
ROTOR_STOP_SPOKE_Z0 = 6.0
ROTOR_STOP_SPOKE_HEIGHT = 6.0

FIXED_STOP_RADIAL_LENGTH = 18.0
FIXED_STOP_TANGENTIAL_WIDTH = 12.0
FIXED_STOP_Z0 = 3.8
FIXED_STOP_TOP_Z = 26.0
FIXED_STOP_HEIGHT = FIXED_STOP_TOP_Z - FIXED_STOP_Z0

ROTOR_STOP_HOME_ANGLE_DEG = 90.0

# Approximate angular half-widths at the shared contact radius. Exact contact is
# subsequently proved with OCC geometry at 14/15/15.5 degrees.
ROTOR_TAB_HALF_ANGLE_DEG = math.degrees(
    math.atan2(ROTOR_STOP_TAB_TANGENTIAL_WIDTH / 2.0, STOP_RADIUS)
)
FIXED_TOWER_HALF_ANGLE_DEG = math.degrees(
    math.atan2(FIXED_STOP_TANGENTIAL_WIDTH / 2.0, STOP_RADIUS)
)
FIXED_STOP_OFFSET_DEG = (
    STOP_TARGET_DEG + ROTOR_TAB_HALF_ANGLE_DEG + FIXED_TOWER_HALF_ANGLE_DEG
)
FIXED_STOP_ANGLE_NEG_DEG = ROTOR_STOP_HOME_ANGLE_DEG - FIXED_STOP_OFFSET_DEG
FIXED_STOP_ANGLE_POS_DEG = ROTOR_STOP_HOME_ANGLE_DEG + FIXED_STOP_OFFSET_DEG

ROTOR_STOP_GLOBAL_BOTTOM_Z = V2.ROTOR_INSTALL_Z + ROTOR_STOP_TAB_Z0
ROTOR_SPOKE_GLOBAL_BOTTOM_Z = V2.ROTOR_INSTALL_Z + ROTOR_STOP_SPOKE_Z0

# Existing fixed ribs outside the v2 rotating clearance top out at ~14 mm.
NONSTOP_FIXED_RIB_TOP_Z = G.BASE_FLOOR_THICKNESS + G.BASE_RIB_HEIGHT
ROTATING_STOP_UNDERSIDE_GAP = (
    min(ROTOR_STOP_GLOBAL_BOTTOM_Z, ROTOR_SPOKE_GLOBAL_BOTTOM_Z)
    - NONSTOP_FIXED_RIB_TOP_Z
)
