#!/usr/bin/env python3
"""v7 parameters: replaceable flush PETG wear surfaces."""

from __future__ import annotations

import math

import geometry_model as G
import v2_params as V2


WEAR_THICKNESS = 1.20
RECESS_EXTRA_DEPTH = 0.10

# Central annular bearing: recess the complete original top annulus so the rotor
# cannot ride on a non-replaceable lip. The insert itself gets radial clearance.
CENTER_RECESS_R_INNER = G.BEARING_INNER_DIAMETER / 2.0
CENTER_RECESS_R_OUTER = G.BEARING_OUTER_DIAMETER / 2.0
CENTER_INSERT_RADIAL_CLEARANCE = 0.35
CENTER_INSERT_R_INNER = CENTER_RECESS_R_INNER + CENTER_INSERT_RADIAL_CLEARANCE
CENTER_INSERT_R_OUTER = CENTER_RECESS_R_OUTER - CENTER_INSERT_RADIAL_CLEARANCE
CENTER_RECESS_Z0 = G.BEARING_TOP_Z - WEAR_THICKNESS
CENTER_RECESS_HEIGHT = WEAR_THICKNESS + RECESS_EXTRA_DEPTH
CENTER_INSERT_INSTALL_Z = CENTER_RECESS_Z0

# Side glide tracks. Recess the complete v2 track sector. The universal wear arc
# is slightly smaller so it drops in without force while retaining >=1.5 deg
# angular travel margin beyond the structural +/-15 deg swivel.
TRACK_RECESS_R_INNER = V2.TRACK_RADIUS - V2.TRACK_RADIAL_WIDTH / 2.0
TRACK_RECESS_R_OUTER = V2.TRACK_RADIUS + V2.TRACK_RADIAL_WIDTH / 2.0
TRACK_INSERT_RADIAL_CLEARANCE = 0.40
TRACK_INSERT_R_INNER = TRACK_RECESS_R_INNER + TRACK_INSERT_RADIAL_CLEARANCE
TRACK_INSERT_R_OUTER = TRACK_RECESS_R_OUTER - TRACK_INSERT_RADIAL_CLEARANCE

TRACK_RECESS_HALF_ANGLE_DEG = G.SWIVEL_LIMIT_DEG + V2.TRACK_ANGLE_MARGIN_DEG
TRACK_INSERT_END_CLEARANCE_DEG = 0.50
TRACK_INSERT_HALF_ANGLE_DEG = (
    TRACK_RECESS_HALF_ANGLE_DEG - TRACK_INSERT_END_CLEARANCE_DEG
)

TRACK_RECESS_Z0 = V2.TRACK_TOP_Z - WEAR_THICKNESS
TRACK_RECESS_HEIGHT = WEAR_THICKNESS + RECESS_EXTRA_DEPTH
TRACK_INSERT_INSTALL_Z = TRACK_RECESS_Z0

# Installed top surfaces remain exactly at the validated v5 planes.
CENTER_INSERT_TOP_Z = CENTER_INSERT_INSTALL_Z + WEAR_THICKNESS
TRACK_INSERT_TOP_Z = TRACK_INSERT_INSTALL_Z + WEAR_THICKNESS

CENTER_INSERT_AREA_MM2 = math.pi * (
    CENTER_INSERT_R_OUTER**2 - CENTER_INSERT_R_INNER**2
)
TRACK_INSERT_AREA_MM2 = (
    0.5
    * (TRACK_INSERT_R_OUTER**2 - TRACK_INSERT_R_INNER**2)
    * math.radians(2.0 * TRACK_INSERT_HALF_ANGLE_DEG)
)

# Internal development pressure check only, same 500 N envelope as baseline.
CENTER_PRESSURE_MPA_AT_500N = G.DESIGN_VERTICAL_LOAD_N / CENTER_INSERT_AREA_MM2
TRACK_PRESSURE_MPA_AT_250N = (
    G.DESIGN_VERTICAL_LOAD_N / 2.0 / TRACK_INSERT_AREA_MM2
)
